version: 2
updates:
  - package-ecosystem: maven
    directory: "/publisher"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/consumer"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/person-app"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
